two_dimension_array: two_dimension_array.o
	cc -o two_dimension_array two_dimension_array.o

two_dimension_array.o: two_dimension_array.c
	cc -c two_dimension_array.c

clean:
	-rm *.out *.o two_dimension_array

